#!/usr/bin/env python3
"""
reindex_wikis.py — Maintain the top-level wiki registry in wikis/_index.md.

Usage:
    python3 reindex_wikis.py <wikis-dir> [--check]

Examples:
    python3 reindex_wikis.py workspace/wikis
    python3 reindex_wikis.py workspace/wikis --check

A workspace holds many isolated wikis under wikis/<name>/. The single bridge
between them is wikis/_index.md, which carries an auto-generated registry block:

    <!-- BEGIN wiki-registry (auto-generated by reindex_wikis.py — do not edit) -->
    - [[erbario/wiki/index|erbario]] — one-line scope from erbario/AGENTS.md
    - [[loops/wiki/index|loops]] — one-line scope from loops/AGENTS.md
    <!-- END wiki-registry -->

Only the text *between* the markers is managed. Everything else in _index.md
(title, curated notes about how the wikis relate) belongs to the agent and is
never touched. `scaffold.py` calls regenerate_index() when it creates a wiki;
`lint_wiki.py --workspace` calls check_index() to detect drift.

Exit codes:
  0 — done (default mode) / registry in sync (--check)
  1 — bad arguments, or registry out of sync (--check)
"""

import re
import sys
from pathlib import Path

BEGIN_MARKER = "<!-- BEGIN wiki-registry (auto-generated by reindex_wikis.py — do not edit) -->"
END_MARKER = "<!-- END wiki-registry -->"

# Matches the managed block including both markers.
BLOCK_RE = re.compile(
    re.escape(BEGIN_MARKER) + r"\n(.*?)\n" + re.escape(END_MARKER),
    re.DOTALL,
)
# Pulls the wiki name out of a registry line: - [[<name>/wiki/index|<name>]] — ...
REGISTRY_LINE_RE = re.compile(r"\[\[([^/\]]+)/wiki/index")

INDEX_FILENAME = "_index.md"
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n", re.DOTALL)


def _is_placeholder(value: str) -> bool:
    return "<" in value and ">" in value


def _frontmatter_scalar(text: str, *keys: str) -> str | None:
    """Return the first present, non-placeholder scalar for any of `keys` from a
    leading YAML frontmatter block. Minimal on purpose (no pyyaml dependency)."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None
    for line in m.group(1).split("\n"):
        if ":" not in line or line.lstrip().startswith("#"):
            continue
        key, _, val = line.partition(":")
        if key.strip() in keys:
            v = val.strip().strip('"').strip("'")
            if v and not _is_placeholder(v):
                return v
    return None


def resolve_wikis_dir(path: str) -> Path:
    """Accept either the wikis/ directory itself or a workspace root that
    contains one. Returns the directory that holds the per-wiki folders."""
    p = Path(path)
    if p.name == "wikis":
        return p
    if (p / "wikis").is_dir():
        return p / "wikis"
    return p


def discover_wikis(wikis_dir: Path) -> list[str]:
    """Immediate subdirectories that look like a wiki root (contain wiki/)."""
    if not wikis_dir.is_dir():
        return []
    names = [
        child.name
        for child in wikis_dir.iterdir()
        if child.is_dir() and (child / "wiki").is_dir()
    ]
    return sorted(names)


def read_wiki_scope(wiki_root: Path) -> str:
    """One-line scope for a wiki, in priority order:

    1. A `summary:` (or `scope:`) field in the YAML frontmatter of the wiki's
       instructions file, `AGENTS.md` — the explicit, stable source.
    2. The first real bullet under "What this wiki covers:" in the `## Scope`
       section.
    3. A neutral fallback, so the registry is always generated deterministically.

    Placeholder values (containing <...>) are ignored at every level."""
    # Stessa regola di ``jafta/utils/wiki_paths.py``, ricopiata a mano e non
    # importata: questo script e' un checkout della skill, destinato a essere
    # copiato nel workspace e modificato dall'utente, non una libreria del
    # package. Il motivo e' lo stesso per cui la logica di scope qui sotto e'
    # gia' una seconda copia.
    #
    # **Un nome solo**, dal passo 7.5: il ripiego su ``CLAUDE.md`` e' stato
    # tolto perche' due nomi per lo stesso file sono due nomi da tenere
    # allineati in ogni lettore, e i lettori sono quattro. Il nome vecchio resta
    # noto a chi lo *rinomina* (``utils/wiki_migration.py``, a ogni avvio), a
    # ``wiki_paths.wiki_id`` e a chi deve solo accorgersi che c'e' per non
    # scriverci accanto un secondo file (``scaffold.py``). Nessuno di quelli
    # legge uno scope. Quindi una wiki non ancora migrata dice
    # «(no AGENTS.md)» — che e' la verita', e la finestra la chiude l'avvio dopo.
    schema = wiki_root / "AGENTS.md"
    if not schema.is_file():
        return "(no AGENTS.md)"
    text = schema.read_text(encoding="utf-8")

    explicit = _frontmatter_scalar(text, "summary", "scope")
    if explicit:
        return explicit

    lines = text.splitlines()
    in_scope = False
    in_covers = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("## "):
            in_scope = stripped[3:].strip().lower() == "scope"
            in_covers = False
            continue
        if not in_scope:
            continue
        if stripped.lower().startswith("what this wiki covers"):
            in_covers = True
            continue
        if in_covers and stripped.startswith("- "):
            bullet = stripped[2:].strip()
            if _is_placeholder(bullet):
                return "(no scope set)"
            return bullet
        if in_covers and stripped.lower().startswith("what this wiki"):
            # Reached the "excludes" subsection without a real bullet.
            break
    return "(no scope set)"


def build_registry_lines(wikis_dir: Path) -> list[str]:
    lines = []
    for name in discover_wikis(wikis_dir):
        scope = read_wiki_scope(wikis_dir / name)
        lines.append(f"- [[{name}/wiki/index|{name}]] — {scope}")
    if not lines:
        lines.append("*(no wikis yet — scaffold one with scaffold.py)*")
    return lines


def _default_index(block_body: str) -> str:
    return (
        "# Workspace Index\n"
        "\n"
        "> Curated notes about how these wikis relate belong above the registry\n"
        "> block. The block below is auto-generated — add wikis with scaffold.py,\n"
        "> don't hand-edit the list.\n"
        "\n"
        f"{BEGIN_MARKER}\n{block_body}\n{END_MARKER}\n"
    )


def regenerate_index(wikis_dir_path) -> Path:
    """Create or update <wikis-dir>/_index.md so the registry block matches the
    wikis on disk. Only the managed block is rewritten. Returns the index path."""
    wikis_dir = resolve_wikis_dir(str(wikis_dir_path))
    wikis_dir.mkdir(parents=True, exist_ok=True)
    index_path = wikis_dir / INDEX_FILENAME
    block_body = "\n".join(build_registry_lines(wikis_dir))

    if not index_path.exists():
        index_path.write_text(_default_index(block_body), encoding="utf-8")
        return index_path

    text = index_path.read_text(encoding="utf-8")
    if BLOCK_RE.search(text):
        new_text = BLOCK_RE.sub(
            lambda _m: f"{BEGIN_MARKER}\n{block_body}\n{END_MARKER}",
            text,
            count=1,
        )
    else:
        # File exists but has no managed block — append one, leaving the rest.
        sep = "" if text.endswith("\n") else "\n"
        new_text = f"{text}{sep}\n{BEGIN_MARKER}\n{block_body}\n{END_MARKER}\n"
        print(
            f"note: {index_path} had no wiki-registry markers — appended a block",
            file=sys.stderr,
        )
    if new_text != text:
        index_path.write_text(new_text, encoding="utf-8")
    return index_path


def check_index(wikis_dir_path) -> list[str]:
    """Return a list of human-readable problems if _index.md's registry is out
    of sync with the wikis on disk. Empty list means in sync."""
    wikis_dir = resolve_wikis_dir(str(wikis_dir_path))
    index_path = wikis_dir / INDEX_FILENAME
    problems: list[str] = []

    if not index_path.exists():
        return [f"{index_path} not found — run reindex_wikis.py to create it"]

    text = index_path.read_text(encoding="utf-8")
    m = BLOCK_RE.search(text)
    if not m:
        return [f"{index_path} has no wiki-registry markers"]

    on_disk = set(discover_wikis(wikis_dir))
    registered = set(REGISTRY_LINE_RE.findall(m.group(1)))

    for name in sorted(on_disk - registered):
        problems.append(f"wiki '{name}' exists on disk but is missing from the registry")
    for name in sorted(registered - on_disk):
        problems.append(f"registry lists '{name}' but no such wiki exists on disk")

    if not problems:
        # Same set of wikis, but scope lines may have drifted.
        expected = "\n".join(build_registry_lines(wikis_dir))
        if m.group(1).strip() != expected.strip():
            problems.append("registry descriptions are out of date (run reindex_wikis.py)")

    return problems


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__)
        return 1
    check = False
    path = None
    for arg in argv[1:]:
        if arg == "--check":
            check = True
        elif arg.startswith("-"):
            print(f"Unknown flag: {arg}", file=sys.stderr)
            return 1
        else:
            path = arg
    if path is None:
        print(__doc__)
        return 1

    wikis_dir = resolve_wikis_dir(path)

    if check:
        problems = check_index(wikis_dir)
        if problems:
            print(f"🔴 wikis/_index.md out of sync ({len(problems)}):")
            for p in problems:
                print(f"   {p}")
            return 1
        print("✅ wikis/_index.md registry is in sync")
        return 0

    index_path = regenerate_index(wikis_dir)
    wikis = discover_wikis(wikis_dir)
    print(f"✓ Regenerated {index_path} — {len(wikis)} wiki(s): {', '.join(wikis) or '(none)'}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
